language: python
python:
  - '2.7'
env:
  global:
    - DB=postgres
  matrix:
    - DJANGO=1.6.2
install:
  - pip install -q coverage flake8 Django==$DJANGO
before_script:
  - flake8 . --max-line-length=120 --max-complexity=10 --exclude='env,migrations,*.egg'
  - psql -c 'CREATE DATABASE user_guide;' -U postgres
script:
  - (cd user_guide/static/user_guide && npm install && npm test)
  - coverage run --source='user_guide' --branch --omit='user_guide/migrations/*' setup.py test
  - coverage report --fail-under=100 --show-missing
