sudo: false
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
env:
  global:
    - DB=postgres
  matrix:
    - DJANGO=">=1.8,<1.9"
    - DJANGO=">=1.9,<1.10"
install:
  - pip install -q coverage flake8 Django$DJANGO django-nose>=1.4
before_script:
  - flake8 .
  - psql -c 'CREATE DATABASE user_guide;' -U postgres
script:
  - (cd user_guide/static/user_guide && npm install && npm test)
  - coverage run setup.py test
  - coverage report --fail-under=100
